# Generated by Django 4.2.6 on 2023-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_blog', '0002_remove_persona_imagen_persona_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('intereses', models.TextField()),
            ],
        ),
    ]
