# Generated by Django 4.2.6 on 2023-11-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_blog', '0003_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
